using System.Text;

namespace TypedPaths.Generator.Utils;

public static class SourceHelper
{
    private static string GetIntent(int level) => new(' ', level * 4);
    
    public static string GenerateRoot(string className, PathNode rootNode)
    {
        var sb = new StringBuilder();
    
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace TypedPaths");
        sb.AppendLine("{");

        sb.Append(GetIntent(1));
        sb.AppendLine("public static partial class TypedPaths");
        sb.Append(GetIntent(1));
        sb.AppendLine("{");

        sb.Append(GetIntent(2));
        sb.AppendLine($"public static partial class {className}");
        sb.Append(GetIntent(2));
        sb.AppendLine("{");
        sb.Append(GetIntent(3));
        sb.AppendLine($"public const string Value = \"{Escape(rootNode.FullPath)}\";");
        sb.AppendLine();

        foreach (var child in rootNode.Children.Values)
        {
            GenerateNest(child, sb, 3);
        }

        sb.Append(GetIntent(2));
        sb.AppendLine("}");
        sb.Append(GetIntent(1));
        sb.AppendLine("}");
    
        sb.AppendLine("}");
    
        return sb.ToString();
    }
    
    private static void GenerateNest(PathNode node, StringBuilder sb, int intentLevel)
    {
        var firstIntent = GetIntent(intentLevel);
        var secondIntent = GetIntent(intentLevel + 1);
        
        sb.AppendLine($"{firstIntent}public static partial class {node.Name}");
        sb.AppendLine($"{firstIntent}{{");
        sb.AppendLine($"{secondIntent}public const string Value = \"{Escape(node.FullPath)}\";");

        if (!node.IsFile)
        {
            sb.AppendLine();
            foreach (var child in node.Children.Values)
            {
                GenerateNest(child, sb, intentLevel + 1);
            }
        }
        
        sb.AppendLine($"{firstIntent}}}");
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", @"\\").Replace("\"", "\\\"");
    }
}