using System.Text;

namespace TypedPaths.Generator.Utils;

public static class SourceHelper
{
    private const string Usings = "using System;";
    
    private const string GeneratedCodeAttribute = "[global::System.CodeDom.Compiler.GeneratedCode(\"TypedPaths.Generator\", \"1.0.0\")]";
    
    private static string GetIntent(int level) => new string(' ', level * 4);
    
    public static string GenerateRoot(string className, PathNode rootNode)
    {
        var sb = new StringBuilder();
    
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace TypedPaths");
        sb.AppendLine("{");

        sb.Append(GetIntent(1));
        sb.AppendLine($"public static partial class {className}");
    
        sb.Append(GetIntent(1));
        sb.AppendLine("{");

        sb.Append(GetIntent(2));
        sb.AppendLine($"public static string Value => \"{rootNode.FullPath}\";");
        sb.Append(GetIntent(2));
        sb.AppendLine("public override string ToString() => Value;");
        sb.AppendLine();

        foreach (var child in rootNode.Children.Values)
        {
            GenerateNest(child, sb, 2);
        }
    
        sb.Append(GetIntent(1));
        sb.AppendLine("}");
    
        sb.AppendLine("}");
    
        return sb.ToString();
    }
    
    private static void GenerateNest(PathNode node, StringBuilder sb, int intentLevel)
    {
        var firstIntent = GetIntent(intentLevel);
        var secondIntent = GetIntent(intentLevel + 1);
        
        sb.AppendLine($"{firstIntent}public static class {node.Name}");
        sb.AppendLine($"{firstIntent}{{");
        
        foreach (var child in node.Children.Values)
        {
            GenerateNest(child, sb, intentLevel + 1);
        }

        sb.AppendLine($"{secondIntent}public static string Value => \"{node.FullPath}\";");
        sb.AppendLine($"{secondIntent}public override string ToString() => Value;");

        sb.AppendLine($"{firstIntent}}}");
    }
}