using TypedPaths.Generator.Utils;

using Xunit;

namespace TypedPaths.Generator.Tests;

/// <summary>
/// Tests for <see cref="SourceHelper.GenerateRoot"/> matching the output shape described in README:
/// namespace TypedPaths, root class (e.g. Src), nested classes with Value and ToString().
/// </summary>
public class SourceHelperTests
{
    [Fact]
    public void GenerateRoot_EmitsAutoGeneratedHeaderAndNamespace()
    {
        var root = new PathNode { Name = "Root", FullPath = "" };
        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("// <auto-generated/>", code);
        Assert.Contains("namespace TypedPaths", code);
        Assert.Contains("public static partial class Src", code);
    }

    [Fact]
    public void GenerateRoot_EmitsRootValueAndToString()
    {
        var root = new PathNode { Name = "Root", FullPath = "src" };
        root.Children["FolderA"] = new PathNode { Name = "FolderA", FullPath = "src/folderA" };

        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("public static string Value => \"src\";", code);
        Assert.Contains("public override string ToString() => Value;", code);
    }

    [Fact]
    public void GenerateRoot_README_Example_SrcFolderATemplate2()
    {
        // README: src/folderA/Template2.anyext => TypedPaths.Src.FolderA.Template2
        var root = new PathNode { Name = "Root", FullPath = "src" };
        var folderA = new PathNode { Name = "FolderA", FullPath = "src/folderA" };
        folderA.Children["Template2"] = new PathNode
        {
            Name = "Template2",
            FullPath = "src/folderA/Template2.anyext"
        };
        root.Children["FolderA"] = folderA;

        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("public static class FolderA", code);
        Assert.Contains("public static string Value => \"src/folderA\";", code);
        Assert.Contains("public static class Template2", code);
        Assert.Contains("public static string Value => \"src/folderA/Template2.anyext\";", code);
    }

    [Fact]
    public void GenerateRoot_README_Example_TemplateEmailWelcome()
    {
        // README: template/email/welcome.txt => TypedPaths.Template.Email.Welcome
        var root = new PathNode { Name = "Root", FullPath = "template" };
        var email = new PathNode { Name = "Email", FullPath = "template/email" };
        email.Children["Welcome"] = new PathNode
        {
            Name = "Welcome",
            FullPath = "template/email/welcome.txt"
        };
        root.Children["Email"] = email;

        string code = SourceHelper.GenerateRoot("Template", root);

        Assert.Contains("public static partial class Template", code);
        Assert.Contains("public static class Email", code);
        Assert.Contains("public static string Value => \"template/email\";", code);
        Assert.Contains("public static class Welcome", code);
        Assert.Contains("public static string Value => \"template/email/welcome.txt\";", code);
    }

    [Fact]
    public void GenerateRoot_MultipleNestedLevels_MatchesREADMEStructure()
    {
        // README: src/folderB/Template3.anyext and Template4.anyext
        var root = new PathNode { Name = "Root", FullPath = "src" };
        var folderB = new PathNode { Name = "FolderB", FullPath = "src/folderB" };
        folderB.Children["Template3"] = new PathNode
        { Name = "Template3", FullPath = "src/folderB/Template3.anyext" };
        folderB.Children["Template4"] = new PathNode
        { Name = "Template4", FullPath = "src/folderB/Template4.anyext" };
        root.Children["FolderB"] = folderB;

        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("public static class FolderB", code);
        Assert.Contains("Value => \"src/folderB\"", code);
        Assert.Contains("Value => \"src/folderB/Template3.anyext\"", code);
        Assert.Contains("Value => \"src/folderB/Template4.anyext\"", code);
    }
}
