using TypedPaths.Generator.Utils;

using Xunit;

namespace TypedPaths.Generator.Tests;

/// <summary>
/// Tests for <see cref="SourceHelper.GenerateRoot"/> matching the output shape described in README:
/// namespace TypedPaths, top-level class per root (e.g. Src), nested classes with Value.
/// </summary>
public class SourceHelperTests
{
    [Fact]
    public void GenerateRoot_EmitsTopLevelClassInTypedPathsNamespace()
    {
        var root = new PathNode { Name = "Root", FullPath = "src", IsFile = false };
        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("// <auto-generated/>", code);
        Assert.Contains("namespace TypedPaths", code);
        Assert.Contains("public static class Src", code);
    }

    [Fact]
    public void GenerateRoot_EmitsValueForFolderAndFileNodes()
    {
        var root = new PathNode { Name = "Root", FullPath = "src", IsFile = false };
        var folder = new PathNode { Name = "FolderA", FullPath = "src/folderA", IsFile = false };
        folder.Children["Template2"] = new PathNode
        {
            Name = "Template2",
            FullPath = "src/folderA/Template2.anyext",
            IsFile = true
        };
        root.Children["FolderA"] = folder;

        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("public const string Value = \"src\";", code);
        Assert.Contains("public static class FolderA", code);
        Assert.Contains("public const string Value = \"src/folderA\";", code);
        Assert.Contains("public static class Template2", code);
        Assert.Contains("public const string Value = \"src/folderA/Template2.anyext\";", code);
    }

    [Fact]
    public void GenerateRoot_FileNode_DoesNotEmitChildren()
    {
        var root = new PathNode { Name = "Root", FullPath = "src", IsFile = false };
        root.Children["Template1"] = new PathNode
        {
            Name = "Template1",
            FullPath = "src/Template1.anyext",
            IsFile = true
        };

        string code = SourceHelper.GenerateRoot("Src", root);

        Assert.Contains("public static class Template1", code);
        Assert.DoesNotContain("public static class Value", code);
    }
}